#!/usr/bin/env python3
"""Fetch legal open-access reading copies of the book's references into private/pdfs/.

For every DOI in references.bib, ask OpenAlex for the best open-access location and
download the PDF where one is offered. Files go to private/pdfs/<key>.pdf, which is
gitignored in both repositories. A manifest at private/reading-copies.md records which
references have an open copy, which were fetched, and which are paywalled and need a
reading copy from the shared folder. Nothing paywalled is fetched, and nothing here is
redistributed.

Usage: python tools/fetch_open_copies.py [--dry-run]
"""
from __future__ import annotations
import argparse
import json
import re
import time
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PDFS = ROOT / 'private' / 'pdfs'
MANIFEST = ROOT / 'private' / 'reading-copies.md'
AGENT = 'metascience-seminar-reading-copies/1.0 (research group reading list)'
TIMEOUT = 60


def openalex(doi: str) -> dict | None:
    url = 'https://api.openalex.org/works/https://doi.org/' + urllib.parse.quote(doi, safe='')
    for attempt in range(3):
        try:
            with urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': AGENT}), timeout=TIMEOUT) as r:
                return json.load(r)
        except urllib.error.HTTPError as exc:
            if exc.code == 404:
                return None
            if exc.code == 429:
                time.sleep(2 ** attempt)
                continue
            return None
        except Exception:  # noqa: BLE001
            time.sleep(1)
    return None


def download(url: str, dest: Path) -> str:
    try:
        req = urllib.request.Request(url, headers={'User-Agent': AGENT, 'Accept': 'application/pdf,*/*'})
        with urllib.request.urlopen(req, timeout=TIMEOUT) as r:
            data = r.read()
            ctype = r.headers.get('Content-Type', '')
    except Exception as exc:  # noqa: BLE001
        return f'failed ({type(exc).__name__})'
    if not data.startswith(b'%PDF'):
        return f'not a PDF ({ctype.split(";")[0] or "unknown type"})'
    dest.write_bytes(data)
    return f'fetched ({len(data) // 1024} KB)'


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--dry-run', action='store_true', help='report availability without downloading')
    args = parser.parse_args()
    bib = (ROOT / 'references.bib').read_text()
    entries = re.findall(r'@\w+\{([^,]+),(.*?)\n\}', bib, flags=re.S)
    PDFS.mkdir(parents=True, exist_ok=True)
    rows = []
    for key, body in entries:
        m = re.search(r'doi = \{([^}]+)\}', body)
        title = re.search(r'title = \{\{?(.*?)\}?\},', body)
        title = title.group(1) if title else key
        if not m:
            rows.append((key, title, 'no DOI', 'book or preprint; see the bibliography entry'))
            continue
        doi = m.group(1)
        work = openalex(doi)
        time.sleep(0.2)
        if not work:
            rows.append((key, title, 'unknown', 'OpenAlex has no record'))
            continue
        oa = work.get('open_access') or {}
        best = work.get('best_oa_location') or {}
        dest = PDFS / f'{key}.pdf'
        if dest.exists():
            rows.append((key, title, 'open', f'already in private/pdfs/ ({best.get("version") or "copy"})'))
            continue
        if not oa.get('is_oa'):
            rows.append((key, title, 'paywalled', 'needs a reading copy from the shared folder'))
            continue
        pdf = best.get('pdf_url')
        landing = best.get('landing_page_url')
        version = best.get('version') or ''
        if args.dry_run:
            rows.append((key, title, 'open', f'{version} at {pdf or landing}'))
            continue
        status = download(pdf, dest) if pdf else 'no direct PDF'
        if not status.startswith('fetched') and landing:
            status2 = download(landing, dest)
            status = status2 if status2.startswith('fetched') else f'{status}; landing page: {landing}'
        rows.append((key, title, 'open', f'{version}: {status}'))
        time.sleep(0.5)
    fetched = sum(1 for r in rows if 'fetched' in r[3] or 'already' in r[3])
    open_n = sum(1 for r in rows if r[2] == 'open')
    pay = sum(1 for r in rows if r[2] == 'paywalled')
    lines = ['# Reading copies', '',
             f'Generated by `tools/fetch_open_copies.py` in the public repository. {len(rows)} references: {open_n} have a legal open copy per OpenAlex ({fetched} fetched into `private/pdfs/`), {pay} are paywalled and need a copy from the shared folder, and the rest are books, preprints, or records OpenAlex does not hold.',
             '', 'Fetched files are named by citation key and are gitignored. Re-run the script after adding references; it skips what is already present.', '',
             '| Key | Title | Access | Note |', '|:--|:--|:--|:--|']
    for key, title, access, note in rows:
        lines.append(f'| `{key}` | {title[:80]} | {access} | {note} |')
    MANIFEST.write_text('\n'.join(lines) + '\n')
    print(f'{len(rows)} references: {open_n} open, {fetched} fetched, {pay} paywalled. Manifest: {MANIFEST.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
